### PR TITLE
Hopefully less hacky method of resolving mcp->obf

### PR DESCRIPTION
**Pull request by TheGlitch76**
This also fixes a problem with forgedev remapping not using the right mappings.
Draft because i'm not 100% sure this didn't break anything yet, need to dig through and see if the issues I'm still having are from this or from Mercury.

### CODE REVIEW

**Comment by ramidzkh** [comment]
What have you tested this on?

**Comment by TheGlitch76** [comment]
Works fine on ExtraGolems once I removed all the javadoc issues

**Comment by TheGlitch76** [comment]
Will do a Forge test and if that works will mark it as ready for review

**Comment by TheGlitch76** [comment]
Seems to be fine.

**Comment by TheGlitch76** [comment]
Superceded by 0ca6e280fd363aa23d1b0b094d8181b6e455b883

**Pull request closed without merging**
